AllCops:
  TargetRubyVersion: 2.4  # Set this to match your project's Ruby version
  Exclude:
    - "bin/*"  # Ignore linting for bin scripts like bin/yarn
    - "node_modules/**/*"
    - "vendor/**/*"
    - db/schema.rb
Style/Documentation:
  Enabled: false  # Disable top-level class/module documentation warnings

Style/MixinUsage:
  Enabled: false  # Disable warnings for `include` at the top level

Lint/Syntax:
  Enabled: true  # Ensure syntax errors are caught
